CREATE DATABASE Accountdb;
CREATE DATABASE GameDB;
CREATE DATABASE logdb;

USE AccountDB;

CREATE TABLE UserAccount
(
id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE KEY,
NAME CHAR(32) NOT NULL PRIMARY KEY,
PASSWORD CHAR(32) NOT NULL,
LoginTime DATETIME,
LogoutTime DATETIME,
CreateTime DATETIME DEFAULT NOW()
)ENGINE=INNODB;



USE GameDB;
DROP TABLE characterinfo;

CREATE TABLE CharacterInfo
(
id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE KEY,
AccountID INT UNSIGNED NOT NULL INDEX COMMENT 'UserAccount id',
NAME CHAR(32) NOT NULL PRIMARY KEY,
CreateTime DATETIME
)ENGINE=INNODB;



USE LogDB;
